# Este volume só será criado efetivamente quando um pod se associar a ele.
# "waiting for first consumer to be created before binding"
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nc-homelab-app-pvc-v3
  namespace: storage-cloud
  labels:
    app: nc-homelab-app-pvc-v3
spec:
  storageClassName: local-path #Opcional pq este é o SC default
  volumeMode: Filesystem  #Opcional pq este é o modo default. (Filesystem or Block)
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
