apiVersion: v1
kind: Service
metadata:
  name: nc-homelab-app-nodeport
  namespace: storage-cloud
spec:
  type: NodePort
  selector:
    app: nc-homelab-app    
    #app: helloworld
  ports:
    - port: 443         # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
      targetPort: 443   # Optional field.
      nodePort: 30443  # Optional field. By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
